version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Node dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running Playwright API tests..."
      - npx playwright test

reports:
  PlaywrightApiTestReports:
    files:
      - 'results.xml'
    base-directory: '.' # Tells CodeBuild to look in the root folder
    file-format: 'JUnitXML'

artifacts:
  files:
    - 'playwright-report/**/*'
  name: PlaywrightTestArtifacts