version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Node dependencies..."
      - npm ci
      - echo "Installing Playwright browsers and system dependencies..."
      - npx playwright install --with-deps
  build:
    commands:
      - echo "Running Playwright API tests..."
      - npx playwright test
artifacts:
  files:
    # This grabs the generated report to save as an artifact
    - playwright-report/**/*
  name: PlaywrightTestReport