version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Node dependencies..."
      - npm ci
      # 🚀 REMOVED --with-deps flag. Only installs lightweight browser binaries (if needed)
      - npx playwright install
  build:
    commands:
      - echo "Running Playwright API tests..."
      - npx playwright test
artifacts:
  files:
    - playwright-report/**/*
  name: PlaywrightTestReport